[2024/04/12 15:23:16] ■■■■■■■■■■■■■■■■■■■■■■■■■■■■
[2024/04/12 15:23:16] Create message python file...:D:\SATERAITO-OFFICE-PROJECT\2nd-GEN-MIGRATION\01.WEB_APPLICATIONS\07.RESOURCE\WANGDA\GEN2\MAIN\src\sateraito_message.py
[2024/04/12 15:23:16] System.IO.IOException: 別のプロセスで使用されているため、プロセスはファイル 'D:\SATERAITO-OFFICE-PROJECT\2nd-GEN-MIGRATION\01.WEB_APPLICATIONS\07.RESOURCE\WANGDA\GEN2\MAIN\src\sateraito_message.py' にアクセスできません。
   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   場所 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   場所 System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   場所 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   場所 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   場所 Ucf.CallClosureCompiler.Program.createLangPyFile()
   場所 Ucf.CallClosureCompiler.Program.executeMainProcess()
   場所 Ucf.CallClosureCompiler.Program.Main(String[] args)
